name: CI Pipeline

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  id-token: write          # Required for requesting the JWT (AWS OIDC)
  contents: read           # Required for actions/checkout
  security-events: write   # Required for uploading Trivy scan results

jobs:
  build-test-deploy:
    uses: FitSync-G13/fitsync-cd-templates/.github/workflows/ci-test-build-push.yml@master
    with:
      service_name: progress-service
      ecr_repository: fitsync-progress-service
      aws_region: us-east-2
      language: 'python'
      python_version: '3.11'
      install_command: 'pip install pytest pytest-asyncio pytest-cov httpx fastapi pydantic python-jose asyncpg redis'
      test_command: 'pytest tests/ --cov=. --cov-report=term-missing'
    # secrets:
    #   AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
